//room modes
global.HARV_MODE = 1;
global.DIST_MODE = 2;
global.ECO_MODE = 3;

//economic statuses
global.ECON_STARVING = -1;
global.ECON_RECOVERING = 1;
global.ECON_STABLE = 2;
global.ECON_SURPLUS = 3;
global.ECON_OVERPRODUCING = 4;

//minimum sell prices
global.RESOURCE_MIN_PRICE = {};
global.RESOURCE_MIN_PRICE[RESOURCE_OXYGEN] = 0.03;
global.RESOURCE_MIN_PRICE[RESOURCE_CATALYST] = 0.140
global.RESOURCE_MIN_PRICE[RESOURCE_LEMERGIUM] = 0.025;
global.RESOURCE_MIN_PRICE[RESOURCE_ZYNTHIUM] = 0.03;
global.RESOURCE_MIN_PRICE[RESOURCE_UTRIUM] = 0.011;
global.RESOURCE_MIN_PRICE[RESOURCE_KEANIUM] = 0.03;
global.RESOURCE_MIN_PRICE[RESOURCE_HYDROGEN] = 0.06;


